<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
		<OutputType>Exe</OutputType>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="TUnit" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\Core\SimCube.Roslynk.Core\SimCube.Roslynk.Core.csproj" />
	</ItemGroup>

</Project>
